import { Button, CheckBox, ListView, LineEdit } from "std-widgets.slint";

// Struct that exports relevant CheckBox properties
export struct TaskItem {
    title: string,
    checked: bool,
}

component ListViewItem inherits GridLayout {
    in-out property <TaskItem> item;
    in-out property <bool> row-has-focus;
    callback row-clicked();
    callback save-item();
    Row {

        HorizontalLayout {
            CheckBox {
                checked: item.checked;
                // Updates TaskItem struct when CheckBox is clicked
        toggled => {
                    item.checked = self.checked;
                }
            }

            LineEdit {
                text: item.title;
            }
        }
    }
}

component AppListView inherits ListView {
    in-out property <[TaskItem]> items;

    // Repeats CheckBox component for every ListView item
    for item in items: ListViewItem {
        item: item;
    }
}

export component AppWindow inherits Window {
    width: 720px;
    height: 640px;
    in-out property <[TaskItem]> items <=> app_listview.items;
    in-out property <string> input_text;
    callback request-add-item();
    callback request-remove-item();

    VerticalLayout {
        width: 100%;
        height: 100%;
        padding: 8px;
        TextInput {
            text <=> input_text;
        }

        HorizontalLayout {
            Button {
                text: "Add";
                clicked => {
                    root.request-add-item();
                }
            }

            Button {
                text: "Remove";
                clicked => {
                    root.request-remove-item();
                }
            }
        }

        app_listview := AppListView { }
    }
}
