import { Button, CheckBox, ListView, LineEdit } from "std-widgets.slint";

// Struct that exports relevant CheckBox properties
export struct TaskItem {
    title: string,
    checked: bool,
}
export struct TabItem {
    title: string,
    items: [TaskItem],
}

component ListViewItem inherits GridLayout {
    in-out property <TaskItem> item;
    in-out property <bool> row-has-focus;
    callback row-clicked();
    callback request-save-item(string);
    callback checkbox-clicked();

    Row {
        HorizontalLayout {
            CheckBox {
                checked: item.checked;
                // Updates TaskItem struct when CheckBox is clicked
                toggled => {
                    root.checkbox-clicked();
                }
            }

            LineEdit {
                text: item.title;
                edited(text) => {
                    root.request-save-item(self.text);
                }
            }
        }
    }
}

component AppListView inherits ListView {
    in-out property <[TaskItem]> items;
    in-out property <bool> pressed;
    callback request-save-item(int, string);

    // Repeats CheckBox component for every ListView item
    for item[i] in items: ListViewItem {
        item: item;
        checkbox-clicked => {
            item.checked = !item.checked;
        }
        request-save-item(update) => {
            root.request-save-item(i, update);
        }
    }
}

component AppTabWidget inherits Window {
    preferred-height: 300px;
    in-out property <int> active-tab;
    in-out property <[TabItem]> items;
    in-out property <string> input-text;

    VerticalLayout {
        tab_bar := HorizontalLayout {
            spacing: 3px;
            for item[index] in items: Button {
                text: item.title;
                clicked => {
                    root.active-tab = index;
                }
            }
        }

        Rectangle {
            for item[index] in items: Rectangle {
                clip: true;
                Rectangle {
                    background: Math.mod(index, 2) == 0 ? red : blue;
                    x: root.active-tab == index ? 0 : root.active-tab < index ? - self.width - 1px : parent.width + 1px;
                    animate x { duration: 125ms; easing: ease; }
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    width: 720px;
    height: 640px;
    in-out property <[TaskItem]> items <=> app_listview.items;
    in-out property <[TabItem]> tab_items <=> app_tabwidget.items;
    in-out property <string> input_text;
    in-out property <string> tab_input <=> app_tabwidget.input_text;
    in-out property <int> active_tab <=> app_tabwidget.active_tab;
    callback request-add-item();
    callback request-remove-checked-items();
    callback request-save-item(int, string);
    callback request-add-tab();
    callback request-remove-tab();

    VerticalLayout {
        width: 100%;
        height: 100%;
        padding: 8px;
        TextInput {
            text <=> input_text;
        }

        HorizontalLayout {
            Button {
                text: "Add";
                clicked => {
                    root.request-add-item();
                }
            }

            Button {
                text: "Remove";
                clicked => {
                    root.request-remove-checked-items();
                }
            }
        }

        app_listview := AppListView {
            request-save-item(index, update) => {
                 root.request-save-item(index, update);
            }
         }

         Rectangle {
            background: whitesmoke;
            border-width: 1px;
            border-color: black;
            TextInput {
                text <=> tab_input;
                preferred-height: 20px;
            }
        }

        HorizontalLayout {
            Button {
                text: "Add Tab";
                clicked => {
                    root.request-add-tab();
                }
            }

            Button {
                text: "Remove Tab";
                clicked => {
                    root.request-remove-tab();
                }
            }
        }

        app_tabwidget := AppTabWidget { }
    }
}
